#!/usr/bin/env bash
# bench.sh — observe the same workload four ways and emit a Markdown results
# table on stdout. Run as root (eBPF + strace need privileges):  sudo ./scripts/bench.sh
#
# The task: count the ERROR lines a process writes, while it runs.
#   baseline     target alone, unobserved (how fast can it go?)
#   ebpf         hook write() in-kernel, check the prefix (target unmodified)
#   pipe|grep    the normal "app | grep" pipeline (cooperative userspace)
#   strace       ptrace every write() (transparent userspace — what eBPF replaces)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

N=${LINES:-200000}
P=${ERRPCT:-10}
TRIALS=${TRIALS:-3}
EXPECTED=$(( N / 100 * P ))

now_ns() { date +%s%N; }

# Minimum wall-time (ms) over TRIALS runs of a command; output discarded.
mintime() {
  local best=0 t0 t1 ms
  for _ in $(seq "$TRIALS"); do
    t0=$(now_ns); "$@" >/dev/null 2>&1 || true; t1=$(now_ns)
    ms=$(( (t1 - t0) / 1000000 ))
    if [ "$best" -eq 0 ] || [ "$ms" -lt "$best" ]; then best=$ms; fi
  done
  echo "$best"
}

TARGET=(./logtarget --lines "$N" --error-pct "$P")

# --- time each method ---
base_ms=$(mintime "${TARGET[@]}")
ebpf_ms=$(mintime ./ebpf_observer -- "${TARGET[@]}")
pipe_ms=$(mintime bash -c "./logtarget --lines $N --error-pct $P | grep -c ERROR")
strace_ms=$(mintime strace -f -s 16 -e trace=write -o /tmp/strace.out "${TARGET[@]}")

# --- correctness: ERROR count each method reports ---
ebpf_cnt=$(./ebpf_observer -- "${TARGET[@]}" 2>/dev/null)
pipe_cnt=$("${TARGET[@]}" | grep -c ERROR || true)
strace -f -s 16 -e trace=write -o /tmp/strace.out "${TARGET[@]}" >/dev/null 2>&1 || true
strace_cnt=$(grep -c '"ERROR' /tmp/strace.out || true)

ok() { [ "$1" = "$EXPECTED" ] && echo "yes" || echo "NO ($1)"; }
kps() { awk -v n="$N" -v ms="$1" 'BEGIN{ printf (ms>0)? "%.0f" : "inf", n/ms }'; }   # K lines/s = N/ms
slow() { awk -v a="$1" -v b="$base_ms" 'BEGIN{ printf "%.1f", (b>0)? a/b : 0 }'; }

cat <<EOF
_Generated by CI on $(date -u +%Y-%m-%d), kernel \`$(uname -r)\`, $(nproc) CPUs. Workload: ${N} lines, ${P}% ERROR, one \`write()\` each (expected ERROR count = ${EXPECTED})._

| method | wall (ms) | throughput (K lines/s) | slowdown vs baseline | ERROR count correct? |
|---|--:|--:|--:|:--:|
| baseline (unobserved) | ${base_ms} | $(kps "$base_ms") | 1.0× | – |
| **eBPF (in-kernel)** | ${ebpf_ms} | $(kps "$ebpf_ms") | $(slow "$ebpf_ms")× | $(ok "$ebpf_cnt") |
| pipe \| grep (userspace) | ${pipe_ms} | $(kps "$pipe_ms") | $(slow "$pipe_ms")× | $(ok "$pipe_cnt") |
| strace / ptrace (userspace) | ${strace_ms} | $(kps "$strace_ms") | $(slow "$strace_ms")× | $(ok "$strace_cnt") |
EOF
