#!/usr/bin/env bash
# bench.sh — observe the same workload four ways and emit a Markdown results
# table on stdout. Run as root (eBPF + strace need privileges):  sudo ./scripts/bench.sh
#
# The task: count the ERROR lines a process writes, while it runs.
#   baseline     target alone, unobserved (how fast can it go?)
#   ebpf         hook write() in-kernel, check the prefix (target unmodified)
#   pipe|grep    the normal "app | grep" pipeline (cooperative userspace)
#   strace       ptrace every write() (transparent userspace — what eBPF replaces)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

N=${LINES:-200000}
P=${ERRPCT:-10}
TRIALS=${TRIALS:-3}
EXPECTED=$(( N / 100 * P ))

now_ns() { date +%s%N; }

# Minimum wall-time (ms) over TRIALS runs of a command; output discarded.
mintime() {
  local best=0 t0 t1 ms
  for _ in $(seq "$TRIALS"); do
    t0=$(now_ns); "$@" >/dev/null 2>&1 || true; t1=$(now_ns)
    ms=$(( (t1 - t0) / 1000000 ))
    if [ "$best" -eq 0 ] || [ "$ms" -lt "$best" ]; then best=$ms; fi
  done
  echo "$best"
}

TARGET=(./logtarget --lines "$N" --error-pct "$P")

# --- time each method ---
base_ms=$(mintime "${TARGET[@]}")
ebpf_ms=$(mintime ./ebpf_observer -- "${TARGET[@]}")
ebpf_co_ms=$(mintime ./ebpf_observer --count-only -- "${TARGET[@]}")  # no user-memory read
pipe_ms=$(mintime bash -c "./logtarget --lines $N --error-pct $P | grep -c ERROR")
strace_ms=$(mintime strace -f -s 16 -e trace=write -o /tmp/strace.out "${TARGET[@]}")

# --- correctness: ERROR count each method reports ---
ebpf_cnt=$(./ebpf_observer -- "${TARGET[@]}" 2>/dev/null)
pipe_cnt=$("${TARGET[@]}" | grep -c ERROR || true)
strace -f -s 16 -e trace=write -o /tmp/strace.out "${TARGET[@]}" >/dev/null 2>&1 || true
strace_cnt=$(grep -c '"ERROR' /tmp/strace.out || true)

ok() { [ "$1" = "$EXPECTED" ] && echo "yes" || echo "NO ($1)"; }
kps() { awk -v n="$N" -v ms="$1" 'BEGIN{ printf (ms>0)? "%.0f" : "inf", n/ms }'; }   # K lines/s = N/ms
slow() { awk -v a="$1" -v b="$base_ms" 'BEGIN{ printf "%.1f", (b>0)? a/b : 0 }'; }
# ns added per write() vs the bare baseline write — the honest "overhead" number.
nsw() { awk -v m="$1" -v b="$base_ms" -v n="$N" 'BEGIN{ printf "%.0f", (m-b)*1e6/n }'; }
base_nsw=$(awk -v b="$base_ms" -v n="$N" 'BEGIN{ printf "%.0f", b*1e6/n }')

# Machine-readable data for scripts/plot.py.
cat > "$ROOT/results.csv" <<CSV
method,wall_ms,throughput_klps,slowdown
baseline,${base_ms},$(kps "$base_ms"),1.0
eBPF,${ebpf_ms},$(kps "$ebpf_ms"),$(slow "$ebpf_ms")
pipe|grep,${pipe_ms},$(kps "$pipe_ms"),$(slow "$pipe_ms")
strace,${strace_ms},$(kps "$strace_ms"),$(slow "$strace_ms")
CSV

cat <<EOF
_Generated by CI on $(date -u +%Y-%m-%d), kernel \`$(uname -r)\`, $(nproc) CPUs. Workload: ${N} lines, ${P}% ERROR, one \`write()\` each (expected ERROR count = ${EXPECTED})._

| method | wall (ms) | throughput (K lines/s) | slowdown vs baseline | ERROR count correct? |
|---|--:|--:|--:|:--:|
| baseline (unobserved) | ${base_ms} | $(kps "$base_ms") | 1.0× | – |
| **eBPF (in-kernel)** | ${ebpf_ms} | $(kps "$ebpf_ms") | $(slow "$ebpf_ms")× | $(ok "$ebpf_cnt") |
| pipe \| grep (userspace) | ${pipe_ms} | $(kps "$pipe_ms") | $(slow "$pipe_ms")× | $(ok "$pipe_cnt") |
| strace / ptrace (userspace) | ${strace_ms} | $(kps "$strace_ms") | $(slow "$strace_ms")× | $(ok "$strace_cnt") |

**Per-\`write()\` overhead (the honest number):** the bare baseline write costs ~${base_nsw} ns. eBPF adds **~$(nsw "$ebpf_ms") ns** (prefix check) — or just **~$(nsw "$ebpf_co_ms") ns** if it only counts (skipping the user-memory read). The big ×'s above are only because the baseline write (to \`/dev/null\`) is nearly free; on a process doing real work per syscall, ~$(nsw "$ebpf_ms") ns is well under 1%.
EOF

# --- big writes: same four methods, but 64 KB per line --------------------
# pipe|grep must copy + scan every byte, so it should balloon; eBPF peeks 5 bytes
# regardless. This is the small-write headline's mirror image.
ratio() { awk -v a="$1" -v b="$2" 'BEGIN{ printf "%.2f", (b>0)? a/b : 0 }'; }
BIGN=${BIGN:-20000}; BIGB=${BIGB:-65536}
TBIG=(./logtarget --lines "$BIGN" --error-pct "$P" --bytes "$BIGB")
bbig=$(mintime "${TBIG[@]}")
ebig=$(mintime ./ebpf_observer -- "${TBIG[@]}")
pbig=$(mintime bash -c "./logtarget --lines $BIGN --error-pct $P --bytes $BIGB | grep -c ERROR")
sbig=$(mintime strace -f -s 16 -e trace=write -o /tmp/strace.out "${TBIG[@]}")
{
  echo "method,wall_ms,slowdown"
  echo "baseline,$bbig,1.00"
  echo "eBPF,$ebig,$(ratio "$ebig" "$bbig")"
  echo "pipe|grep,$pbig,$(ratio "$pbig" "$bbig")"
  echo "strace,$sbig,$(ratio "$sbig" "$bbig")"
} > "$ROOT/results_big.csv"

# --- use-case sweep: vary message size -----------------------------------
# eBPF's cost is per-EVENT (it peeks 5 bytes regardless of size); pipe|grep must
# move and scan every byte. So tiny messages favor pipe|grep, big messages favor
# eBPF. strace is omitted (constant-bad, and slow). Writes to /dev/null except
# the pipe path. Results -> sizes.csv for the second chart.
SIZES=${SIZES:-"64 256 1024 4096 16384 65536"}
SWEEP_N=${SWEEP_N:-20000}
SIZES_CSV="$ROOT/sizes.csv"
sl() { awk -v a="$1" -v b="$bms" 'BEGIN{ printf "%.2f", (b>0)? a/b : 0 }'; }
echo "method,bytes,wall_ms,slowdown" > "$SIZES_CSV"
for B in $SIZES; do
  bms=$(mintime ./logtarget --lines "$SWEEP_N" --bytes "$B")
  ems=$(mintime ./ebpf_observer -- ./logtarget --lines "$SWEEP_N" --bytes "$B")
  pms=$(mintime bash -c "./logtarget --lines $SWEEP_N --bytes $B | grep -c ERROR")
  echo "baseline,$B,$bms,1.00"          >> "$SIZES_CSV"
  echo "eBPF,$B,$ems,$(sl "$ems")"      >> "$SIZES_CSV"
  echo "pipe|grep,$B,$pms,$(sl "$pms")" >> "$SIZES_CSV"
done

# --- same-core: pin everything to ONE cpu (taskset -c 0) ------------------
# pipe|grep's edge was that grep ran on a spare core. Take it away and grep
# fights the process for the CPU; eBPF runs inline in the kernel and doesn't care.
PIN="taskset -c 0"
ratio() { awk -v a="$1" -v b="$2" 'BEGIN{ printf "%.2f", (b>0)? a/b : 0 }'; }
b1=$(mintime $PIN ./logtarget --lines "$N" --error-pct "$P")
e1=$(mintime $PIN ./ebpf_observer -- ./logtarget --lines "$N" --error-pct "$P")
p1=$(mintime $PIN bash -c "./logtarget --lines $N --error-pct $P | grep -c ERROR")
s1=$(mintime $PIN strace -f -s 16 -e trace=write -o /tmp/strace.out ./logtarget --lines "$N" --error-pct "$P")
{
  echo "method,cpus,slowdown"
  echo "baseline,all cores,1.00"
  echo "eBPF,all cores,$(ratio "$ebpf_ms" "$base_ms")"
  echo "pipe|grep,all cores,$(ratio "$pipe_ms" "$base_ms")"
  echo "strace,all cores,$(ratio "$strace_ms" "$base_ms")"
  echo "baseline,1 core,1.00"
  echo "eBPF,1 core,$(ratio "$e1" "$b1")"
  echo "pipe|grep,1 core,$(ratio "$p1" "$b1")"
  echo "strace,1 core,$(ratio "$s1" "$b1")"
} > "$ROOT/cores.csv"
